### ISSUE TITLE
"Missing required module 'XCTest_Gherkin_ObjC'"

### ISSUE THREAD

**Issue by tomleightonstars** [net-a-porter-mobile/XCTest-Gherkin#177]
I just imported the project via the Swift Package Manager and I'm getting the error "Missing required module 'XCTest_Gherkin_ObjC'" when doing "import XCTest_Gherkin" in a Swift project.

Any ideas if something's broken or I'm doing something wrong?

Edit: I'm using Xcode 12.4

**Comment by kerrmarin** [comment]
Hi @tomleightonstars, thanks for opening this issue. Can you provide a small project that reproduces the issue?

**Comment by tomleightonstars** [comment]
solved tihs by using cocoapods

**Comment by olmedocr** [comment]
This happens because SPM does not link frameworks to testing targets at the moment, you can check a better explanation and the solution [here](https://stackoverflow.com/questions/58125428/missing-required-module-xyz-on-unit-tests-when-using-swift-package-manager).
In any case, it keeps failing with the error `ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'`
Could be [this](https://stackoverflow.com/questions/36065748/swift-package-manager-undefined-symbols-for-architecture-x86-64-from-command-l) problem @kerrmarin ?
