### ISSUE TITLE
Feature request: execute multiple scenario's in one native feature file in specified order

### ISSUE THREAD

**Issue by smaljaar** [net-a-porter-mobile/XCTest-Gherkin#35]
When multiple scenario's are defined in one native feature file they are executed in reversed alphabetical order. This is caused by the line of code in NativeTestCase.swift:

> testCaseClass.testInvocations().sort { (a,b) in NSStringFromSelector(a.selector) > NSStringFromSelector(b.selector) }

Without this sort operation the test invocations (aka 'scenarios') are executed in alphabetical order, which is natural for tests in an XCTestCase class. However, I found this unexpected behaviour when executing multiple scenario's from one native feature file. I would expect the scenario's to be executed in the order that they are specified. 

My proposal is to remove the sort operation, and implement/refactor 'something' which makes sure that the scenario's are executed in the order that they are specified in the native feature file. 

Any ideas, suggestions?

**Comment by nap-sam-dean** [comment]
I'll be honest - I have no idea why that sort is there. I suspect to make the order consistent while I was debugging it, though you're right; the order is somewhat strange! I would also expect the test cases to be executed in the order they are defined. I can think of two ways to do this:

* Add a property to NativeScenario which is it's position in the feature (though this will probably just be it's index in the NativeFeature's scenarios collection). Use this number instead of the selector name when sorting the tests

* Add a number to the dynamically created test method name so that they run in the right order automagically (though this is relying on XCode being consistent in it's test run implementation!)

**Comment by kerrmarin** [comment]
How is number 2 relying on Xcode? Assuming that we change the name of the test selector, and we maintain the call to `sort`, the order would be defined by that?

I don't have a strong preference for either, but perhaps number 2 would be slightly simpler to implement and understand.

**Comment by nap-sam-dean** [comment]
Ah - yes you're right, we run each test ourselves inside that loop. Number 2 doesn't depend on Xcode at all! As long as we check that sort puts `test2MySecondTest` after `test10MyTenthTest` we should be fine :) I guess this is what unit tests are for!

**Comment by smaljaar** [comment]
@kerrmarin I agree with the option "Add a number to the dynamically created test method name" for simplicity reasons, and to keep a sorting operation in place so we don't need to rely on Xcode's sorting of tests in a XCTestCase class 
@nap-sam-dean the sort should put test2MySecondTest _before_ test10MyTenthTest right..?

**Comment by nap-sam-dean** [comment]
@smaljaar I've updated my comment :)

**Comment by nap-sam-dean** [comment]
@kerrmarin I guess this can be closed now #65 is merged?

**Comment by kerrmarin** [comment]
Yup
