### ISSUE TITLE
Data Tables?

### ISSUE THREAD

**Issue by ilife** [net-a-porter-mobile/XCTest-Gherkin#41]
Given the following users exist:
  | name   | email              | twitter         |
  | Aslak  | aslak@cucumber.io  | @aslak_hellesoy |
  | Julien | julien@cucumber.io | @jbpros         |
  | Matt   | matt@cucumber.io   | @mattwynne      |

Can I use data tables with XCTest-Gherkin? If yes, then, what is the correct way to define steps?

**Comment by nap-sam-dean** [comment]
Hi,

This should work absolutely fine like this:

```
func testOutlineTests() {
        Examples(
            [ "name", "email", "twitter" ],
            [ "Aslak", "aslak@cucumber.io", "@aslak_hellesoy" ],
            [ "Julien", "julien@cucumber.io", "@jbpros" ],
            [ "Matt", "matt@cucumber.io", "@mattwynne" ]
        )

        Outline {
            Given("I use the example name <name>")
            Then("The email should be <email>")
            And("The twitter should be <twitter>")
        }
    }
```

**Comment by ilife** [comment]
In the above solution provided by you, outline executes iteratively one example at a time. But, I am talking about this:
https://www.relishapp.com/cucumber/cucumber-tck/docs/data-tables

Here all the values for the given step are passed only once.

**Comment by nap-sam-dean** [comment]
Yes, that's because my answer is a hack that works around the fact we don't have support for data tables (yet) :)

The step(s) in the Outline block are run once per line in the example data.

The steps after the Outline block are then run once.

You would have to modify your single step to allow it to be run multiple times, but with a bit of a tweak the end result would be the same.

Alternatively, please suggest a way we could incorporate this into the library!
