### ISSUE TITLE
Swift 2.3/3.0 support?

### ISSUE THREAD

**Issue by DarkSatyr** [net-a-porter-mobile/XCTest-Gherkin#43]
Hi everyone,
Are you going to add Swift 2.3 or 3.0 support anytime soon? When this can be?

**Comment by nap-sam-dean** [comment]
I guess the cheeky answer would be "whenever your pull request gets approved" ;)

We're moving directly to Swift 3 here, so that will probably be the first thing we look at. We'll probably also get a swift 2.3 branch as well for backwards compatibility, though that branch won't be actively developed.

**Comment by nap-sam-dean** [comment]
Hi,

@Rabursky has just submitted a pull request which adds Swift 3 support (and lets it work on Xcode8) so as soon as that is merged in and released, you should be good to carry on with swift 3 :)

**Comment by irskep** [comment]
Your move to 3.0 (skipping 2.3) means I can no longer use your repo. It would be great if you could make a git tag in this repo that adds this commit: https://github.com/irskep/XCTest-Gherkin/commit/2c2c667b7a7c75d8215fd12ea50e89fd351ecafa

Also, at some point you broke Carthage support by removing the shared scheme for building the framework. I added it back.

I would submit a PR, but I can't work against master anymore due to Swift 3. I'm happy to do this in PR form if you give me a branch to submit against.

**Comment by nap-sam-dean** [comment]
@irskep First, obviously, sorry and oops :) I've made a branch `feature/swift23` which contains your commit so you can continue to work from there, and if you (or other swift 2.3 users) need to make any other changes then they can be PR'd into there.

RE: carthage support - I don't know anything about Carthage really, so had no idea we had broken it! What do we do to fix this on master as well; is it just re-sharing the XCTest-Gherkin scheme?

**Comment by irskep** [comment]
All you need to do is re-share the scheme that builds the framework. That's all Carthage needs. Its whole design is to scan your xcodeproj/xcworkspace for shared framework schemes.

**Comment by irskep** [comment]
Thanks for being so responsive! I imagine the `feature/swift23` branch will not need much maintenance, since Swift 2.3 is a transitional version anyway.

**Comment by nap-sam-dean** [comment]
Hi @Rabursky - can you take a look at this PR please https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/47 and let me know if that's all I need to do?

Thanks!

**Comment by nap-sam-dean** [comment]
Hi @DarkSatyr - can you confirm that the latest release builds in swift 3.0 for you, and then I can close this issue? Thanks.

**Comment by DarkSatyr** [comment]
Hi @nap-sam-dean everything works fine, thanks
sorry for late response

**Comment by nap-sam-dean** [comment]
No worries - glad it's all working :)
