### ISSUE TITLE
Step not executed when poorly named

### ISSUE THREAD

**Issue by tomesm** [net-a-porter-mobile/XCTest-Gherkin#95]
I am experiencing a strange issue.

If I have a step named as "I tap email button" it is simply not executed. It is not matter if it is Given/And/When/Then ... step("I tap email button") {...} is simply not executing.

The problem is "email button". If you put these two words in any existing step names, the step is simply not executed. Which is quite disturbing if you need to test inputs for... email button :)

Can I hope this will be fixed in the near future?

**Comment by kerrmarin** [comment]
Hey @tomesm can you please upload/show us a project that has this issue? Thanks!

**Comment by tomesm** [comment]
@kerrmarin There is EmailTestSteps class: https://pastebin.com/PmVKtabU

And here WelcomeFeatureSteps class: https://pastebin.com/6hxYjres

I have finally figured out what is happening. The problem is substring "email button". If the same substring is present in several steps in several Classes, it causes a problem.

If I execute EmailTestSteps the **step("I tap email button")** is not executed. Instead, **step("email button")** from WelcomeFeatureSteps is executed. After that it jumps back into EmailTestSteps and **step("I put invalid (.*)") { (address: String) in  }** is executed (and test crashes).

Here is the folder tree structure: https://pastebin.com/xavwVJnw
You can see both Classes are in separate folders under parent UITests folder

Can not show the whole project as it is proprietary. I hope it is understood that the problem is same substrings in two steps.

**Comment by kerrmarin** [comment]
Hey @tomesm, the reason you're getting that error is because there is ambiguity between your steps, and the step resolver executes the first step it finds that 'matches' your regular expression. To fix this, you can change your steps to be more specific e.g. change your step for 'email button' to `step("^email button$") {`. This will remove the ambiguity and the correct steps will be run. Let me know how you get on!

**Comment by kerrmarin** [comment]
Also, this is the most popular issue we get, I'd love to hear if you have some feedback on how we can make this more explicit to the user so it's obvious to a user of this library that there is ambiguity caused by loose-fitting regular expressions.

**Comment by deanWombourne** [comment]
I wonder if there is a more reasonable choice the library could make when there is ambiguity? i.e. If we have two steps 

`i tap email button`
`email button`

and we try to match `I tap email button` then it would make more sense to match the first step, not the second? Though I don't know what the rules here would be - amount of matched text perhaps?

**Comment by tomesm** [comment]
@kerrmarin Well, this might help as a short-term solution but its actually sucks :) Consider 5 or more steps for testing several kinds of checkboxes. The step will contain several

`checkbox on` or `checkbox off` substrings... in a big project (and the one I am working on is pretty huge) I will run out of special characters soon :)

Checking the length of the string as @deanWombourne sugessts would be definitely an improvement (not a solution though).

I will discuss this with my team and perhaps we will figure out something.

**Comment by kerrmarin** [comment]
Hey @tomesm, sorry I think I didn't explain enough. The `^` and `$` aren't just any special characters, they're regular expression delimiters for start and end of string (see: https://www.regular-expressions.info/anchors.html). Steps are matched using regular expressions, so by using the anchors you are telling the step that it _must_ match a string that starts at the character after `^` and ends at the character before `$`. Here's a quick example:

The string:
`email button`
will match both of these expressions:
`i tap email button`
`email button`
because they both contain `email button`. But if you changed your regular expressions to be:
`i tap email button`
`^email button$`
it will now only match the second expression, because the anchors force it to begin and end at the specified locations.

@deanWombourne perhaps we could have a "setting/flag" that auto-magically adds `^` and `$` to all steps? Is there a time where we actually want this ambiguity?

**Comment by deanWombourne** [comment]
`step("I tap email button", exact: true`) { ... }` ?

**Comment by deanWombourne** [comment]
Ideally we want to preserve the ambiguity, not because we want the ambiguity, but because we don't know how many other users of this library are relying on this without knowing it :) For every ambiguous step reported as not working, I bet there are others where it chooses the right one so we never hear them!

**Comment by tomesm** [comment]
@kerrmarin ok now I understand. Thanks for explanation. I am a junior developer and I am not familiar with regular expressions. In this case we can solve this with exact matches and thats it. 

@deanWombourne perhaps another README update with a simple note about regex usage would be enough (or put an example into an Example project).

**Comment by deanWombourne** [comment]
@tomesm Don't worry about not being familiar with regular expressions, they're a vast nightmare and will always surprise you in new and exciting ways! I've made a PR with your suggestions in here: #96 if you're interested / have feedback.
